#!/usr/bin/env python3

from __future__ import unicode_literals

#https://pypi.python.org/pypi/argon2_cffi/
import argon2
import string
import math
import argparse
import sys
import getpass
import configparser
import os
import paramiko
import pyperclip

from prompt_toolkit import PromptSession, prompt
from prompt_toolkit.completion import FuzzyWordCompleter
from prompt_toolkit.validation import Validator
from prompt_toolkit.history import FileHistory
from prompt_toolkit.auto_suggest import AutoSuggestFromHistory

ARGON2_VERSION = argon2.__version__

args = {}
config = configparser.ConfigParser({
    "website": "",
    "username": "",

    "length": "16",
    "charset": "luns",
    "symbols": "",
    "revision": "",

    "time": "16",
    "memory": "1024",
    "threads": "16",
    "argon2version": "",
})

def strlen2bytecount(charcount, length):
    bytes = int(math.log(math.pow(charcount,length),2)/8)
    return bytes

def bin2ascii(chars, x):
    sum = 0
    for i in range(len(x)):
        sum <<= 8
        sum += x[i]

    ret = ""
    while sum > 0:
        z = sum % len(chars)
        ret += chars[z]
        sum //= len(chars)
    return ret;

class Site:
    def __init__(self, section):
        self.name = section
        self.url = config.get(section, "website")
        self.username = config.get(section, "username")
        self.length = config.getint(section, "length")
        self.charset = config.get(section, "charset")
        self.symbols = config.get(section, "symbols")
        self.revision = config.get(section, "revision")
        self.time = config.getint(section, "time")
        self.memory = config.getint(section, "memory")
        self.threads = config.getint(section, "threads")
        self.argon2version = config.get(section, "argon2version")

        if self.argon2version and self.argon2version != ARGON2_VERSION:
            print("WARNING: argon2 version differs. Passwords may be incorrect (have {}, want {})"
                  .format(ARGON2_VERSION, self.argon2version), file=sys.stderr)

    def hash(self, password, salt, byteCount):
        return argon2.hash_password_raw(
            bytes(password, "utf-8"),
            bytes(salt, "utf-8"),
            hash_len=byteCount,
            time_cost=self.time,
            memory_cost=self.memory,
            parallelism=self.threads,
            type=argon2.Type.I
        )


    def getPassword(self, masterPassword):
        chars = "";
        if "l" in self.charset:
            chars += string.ascii_lowercase
        if "u" in self.charset:
            chars += string.ascii_uppercase
        if "n" in self.charset:
            chars += string.digits
        if self.symbols:
            chars += self.symbols
        else:
            if "s" in self.charset:
                chars += string.punctuation+" "
            if "S" in self.charset:
                chars += "!@#$%^&*()-=_+"


        identity = self.name+self.username+self.revision
        byteCount = strlen2bytecount(len(chars), self.length)
        return bin2ascii(chars, self.hash(masterPassword, identity, byteCount))

def inputOption(section, option):
    value = input(option+" ("+config.defaults()[option]+"): ")
    if value:
        config.set(section, option, value)

def createSite(name):
    config.add_section(name)
    inputOption(name, "website")
    inputOption(name, "username")
    inputOption(name, "charset")
    inputOption(name, "length")
    with openConfig(args.config, args.remote, 'w') as file:
        config.write(file)

def removeSite(name):
    config.remove_section(name)
    with openConfig(args.config, args.remote, 'w') as file:
        config.write(file)

def updateSite(name):
    try:
        revision = config.getint(name, "revision")
    except:
        revision = 0
    config.set(name, "revision", str(revision+1))
    with openConfig(args.config, args.remote, 'w') as file:
        config.write(file)
    return revision

def getSite(config, site):
    if not site:
        if sys.stdin.isatty():
            histfile = os.getenv('ARGONHIST')
            if histfile:
                session = PromptSession(history=FileHistory(histfile))
            else:
                session = PromptSession()

            def validate_site(text):
                return (text in config.sections())

            site_completer = FuzzyWordCompleter(config.sections)
            site_validator = Validator.from_callable(validate_site, error_message="Site not found", move_cursor_to_end=True)
            site = session.prompt("Site: ",
                               auto_suggest=AutoSuggestFromHistory(),
                               completer=site_completer, complete_while_typing=True,
                               validator=site_validator, validate_while_typing=False)
        else:
            parser.print_usage(sys.stderr)
            sys.exit(1)

    if config.has_section(site):
        site = Site(site)
        return site
    else:
        print("Site not found", file=sys.stderr)
        sys.exit(1)

def getPassword(site):
    if sys.stdin.isatty():
        password = prompt("Enter your master password: ", is_password=True)
    else:
        password = sys.stdin.readline().rstrip("\r\n")

    return site.getPassword(password)

def openConfig(path, remote=None, mode='r'):
    if remote:
        # Home expansion not supported. Assume that cwd will be home by default
        path = path.replace("~/", "")

        port = 22
        if ':' in remote:
            remote, port = remote.split(':', 1)
        if '@' in remote:
            user, remote = remote.split('@', 1)

        client = paramiko.SSHClient()
        client.load_system_host_keys()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(hostname=remote, username=user, port=port,
                    look_for_keys=True, allow_agent=True)
        sftp = client.open_sftp()
        return sftp.open(path, mode)
    else:
        return open(os.path.expanduser(path), mode)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("site", nargs='?')
    parser.add_argument("--config", default='~/.argonpass')
    parser.add_argument("-r", "--remote", default=None)
    parser.add_argument("-l", "--list", action="store_true")
    parser.add_argument("-i", "--info", action="store_true")
    parser.add_argument("-w", "--website", action="store_true")
    parser.add_argument("-u", "--user", action="store_true")
    parser.add_argument("-p", "--password", action="store_true")
    parser.add_argument("-n", "--new", action="store_true")
    parser.add_argument("-d", "--delete", action="store_true")
    parser.add_argument("-c", "--change", action="store_true")
    parser.add_argument("-x", "--clipboard", action='store_true')

    args = parser.parse_args()

    try:
        with openConfig(args.config, args.remote) as file:
            config.read_file(file)
    except Exception as e:
        print(e)
        sys.exit(1)

    try:
        if args.list:
            for section in config.sections():
                print(section)
            sys.exit(0)

        if not args.site:
            parser.print_usage()
            sys.exit(1)

        # Changes
        if args.new:
            createSite(args.site)
            sys.exit(0)
        elif args.change:
            rev = updateSite(args.site)
            print("Revision now %i".format(rev))
            sys.exit(0)
        elif args.delete:
            removeSite(args.site)
            sys.exit(0)

        site = getSite(config, args.site)

        # Queries
        if args.info:
            if site.url:
                print("Website: "+site.url)
            print("Username: "+site.username)
            print("")
            print("Length: "+str(site.length))
            print("Charset: "+str(site.charset))
            if site.revision:
                print("Revision: "+site.revision)
            print("")
            print("Time: "+str(site.time))
            print("Memory: "+str(site.memory))
            print("Threads: "+str(site.threads))
            sys.exit(0)

        if not args.info and not args.password and not args.user and not args.website:
            args.password = True
        if args.password:
            sitepass = getPassword(site)

        if args.website:
            print(site.url)
            if args.clipboard:
                pyperclip.copy(site.url)
        if args.user:
            print(site.username)
            if args.clipboard:
                pyperclip.copy(site.username)
        if sitepass:
            print(sitepass)
            if args.clipboard:
                pyperclip.copy(sitepass)

    except KeyboardInterrupt:
        sys.exit(0)
